SECRET_KEY = "9dsj38gj3j9fcjsaojfADf8"
CUBE_API_SERVICE = "http://localhost:8182"
SUBMIT_URL = "/submit/puzzle/%s"
GOOGLE_API_KEY = "AIzaSyCDkIrVkWdEaOqWe2tPRRmspwL26pU71GI"
AWS_ASSET_BUCKET = "eastern-toys-assets"
AWS_ASSET_ACCESS_KEY = "AKIAIAR4CIFKO4DGX4WQ"
AWS_ASSET_SECRET_KEY = "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"
PROPAGATE_EXCEPTIONS = True
